local DataService = require(script.Parent.Services.DataService)
local InventoryService = require(script.Parent.Services.InventoryService)
local ProgressionService = require(script.Parent.Services.ProgressionService)
local PlayerUIService = require(script.Parent.Services.PlayerUIService)
local CurrencyService = require(script.Parent.Services.CurrencyService)
local DisplayCounterService = require(script.Parent.Services.DisplayCounterService)
local CookingService = require(script.Parent.Services.CookingService)
local IngredientPickupService = require(script.Parent.Services.IngredientPickupService)
local ObbyRewardService = require(script.Parent.Services.ObbyRewardService)
local PrototypeWorldService = require(script.Parent.Services.PrototypeWorldService)
local DisplayCounterVisualService = require(script.Parent.Services.DisplayCounterVisualService)
local CustomerService = require(script.Parent.Services.CustomerService)
local RestaurantService = require(script.Parent.Services.RestaurantService)

-- DataService must init first so player profiles are loaded before
-- any other service accesses player data through GetData.
DataService:Init()
PrototypeWorldService:Init()
RestaurantService:Init()
InventoryService:Init()
ProgressionService:Init()
CurrencyService:Init()
PlayerUIService:Init()
DisplayCounterService:Init()
DisplayCounterVisualService:Init()
CookingService:Init()
IngredientPickupService:Init()
ObbyRewardService:Init()
CustomerService:Init()
